import { Level, Direction, Color } from "../game"

const level: Level = {
    ship: {
        row: 10, col: 1, direction: Direction.TOP
    },
    functions: [5, 5],
    paintAvailability: { red: false, green: false, blue: false },
    cells: [
        { row: 1, col: 1, color: Color.NONE },
        { row: 2, col: 1, color: Color.NONE },
        { row: 3, col: 1, color: Color.NONE },
        { row: 4, col: 1, color: Color.NONE },
        { row: 5, col: 1, color: Color.NONE },
        { row: 6, col: 1, color: Color.NONE },
        { row: 7, col: 1, color: Color.BLUE },
        { row: 8, col: 1, color: Color.RED },
        { row: 9, col: 1, color: Color.RED },
        { row: 10, col: 1, color: Color.RED },

        { row: 1, col: 2, color: Color.BLUE },
        { row: 2, col: 2, color: Color.RED },
        { row: 3, col: 2, color: Color.RED },
        { row: 4, col: 2, color: Color.RED },
        { row: 5, col: 2, color: Color.RED },
        { row: 6, col: 2, color: Color.RED },
        { row: 7, col: 2, color: Color.RED },
        { row: 8, col: 2, color: Color.RED },
        { row: 9, col: 2, color: Color.RED },
        { row: 10, col: 2, color: Color.RED },
        { row: 11, col: 2, color: Color.RED },

        { row: 1, col: 3, color: Color.NONE },
        { row: 2, col: 3, color: Color.NONE },
        { row: 3, col: 3, color: Color.BLUE },
        { row: 4, col: 3, color: Color.RED },
        { row: 5, col: 3, color: Color.RED },
        { row: 6, col: 3, color: Color.RED },
        { row: 7, col: 3, color: Color.RED },
        { row: 8, col: 3, color: Color.RED },
        { row: 9, col: 3, color: Color.RED },
        { row: 10, col: 3, color: Color.RED },
        { row: 11, col: 3, color: Color.RED },
        { row: 12, col: 3, color: Color.RED },

        { row: 1, col: 4, color: Color.NONE },
        { row: 2, col: 4, color: Color.NONE },
        { row: 3, col: 4, color: Color.NONE },
        { row: 4, col: 4, color: Color.NONE },
        { row: 5, col: 4, color: Color.NONE },
        { row: 6, col: 4, color: Color.NONE },
        { row: 7, col: 4, color: Color.BLUE },
        { row: 8, col: 4, color: Color.RED },
        { row: 9, col: 4, color: Color.RED },
        { row: 10, col: 4, color: Color.RED },
        { row: 11, col: 4, color: Color.RED },
        { row: 12, col: 4, color: Color.RED },
        { row: 13, col: 4, color: Color.RED },

        { row: 1, col: 5, color: Color.BLUE },
        { row: 2, col: 5, color: Color.RED },
        { row: 3, col: 5, color: Color.RED },
        { row: 4, col: 5, color: Color.RED },
        { row: 5, col: 5, color: Color.RED },
        { row: 6, col: 5, color: Color.RED },
        { row: 7, col: 5, color: Color.RED },
        { row: 8, col: 5, color: Color.RED },
        { row: 9, col: 5, color: Color.RED },
        { row: 10, col: 5, color: Color.RED },
        { row: 11, col: 5, color: Color.RED },
        { row: 12, col: 5, color: Color.RED },
        { row: 13, col: 5, color: Color.RED },
        { row: 14, col: 5, color: Color.RED },

        { row: 1, col: 6, color: Color.NONE },
        { row: 2, col: 6, color: Color.NONE },
        { row: 3, col: 6, color: Color.NONE },
        { row: 4, col: 6, color: Color.BLUE },
        { row: 5, col: 6, color: Color.RED },
        { row: 6, col: 6, color: Color.RED },
        { row: 7, col: 6, color: Color.RED },
        { row: 8, col: 6, color: Color.RED },
        { row: 9, col: 6, color: Color.RED },
        { row: 10, col: 6, color: Color.RED },
        { row: 11, col: 6, color: Color.RED },
        { row: 12, col: 6, color: Color.RED },
        { row: 13, col: 6, color: Color.RED },
        { row: 14, col: 6, color: Color.RED },
        { row: 15, col: 6, color: Color.RED },

        { row: 1, col: 7, color: Color.NONE },
        { row: 2, col: 7, color: Color.NONE },
        { row: 3, col: 7, color: Color.NONE },
        { row: 4, col: 7, color: Color.NONE },
        { row: 5, col: 7, color: Color.NONE },
        { row: 6, col: 7, color: Color.BLUE },
        { row: 7, col: 7, color: Color.RED },
        { row: 8, col: 7, color: Color.RED },
        { row: 9, col: 7, color: Color.RED },
        { row: 10, col: 7, color: Color.RED },
        { row: 11, col: 7, color: Color.RED },
        { row: 12, col: 7, color: Color.RED },
        { row: 13, col: 7, color: Color.RED },
        { row: 14, col: 7, color: Color.RED },
        { row: 15, col: 7, color: Color.RED },

        { row: 1, col: 8, color: Color.NONE },
        { row: 2, col: 8, color: Color.NONE },
        { row: 3, col: 8, color: Color.BLUE },
        { row: 4, col: 8, color: Color.RED },
        { row: 5, col: 8, color: Color.RED },
        { row: 6, col: 8, color: Color.RED },
        { row: 7, col: 8, color: Color.RED },
        { row: 8, col: 8, color: Color.RED },
        { row: 9, col: 8, color: Color.RED },
        { row: 10, col: 8, color: Color.RED },
        { row: 11, col: 8, color: Color.RED },
        { row: 12, col: 8, color: Color.RED },
        { row: 13, col: 8, color: Color.RED },
        { row: 14, col: 8, color: Color.RED },
        { row: 15, col: 8, color: Color.RED },

        { row: 1, col: 9, color: Color.NONE },
        { row: 2, col: 9, color: Color.NONE },
        { row: 3, col: 9, color: Color.NONE },
        { row: 4, col: 9, color: Color.BLUE },
        { row: 5, col: 9, color: Color.RED },
        { row: 6, col: 9, color: Color.RED },
        { row: 7, col: 9, color: Color.RED },
        { row: 8, col: 9, color: Color.RED },
        { row: 9, col: 9, color: Color.RED },
        { row: 10, col: 9, color: Color.RED },
        { row: 11, col: 9, color: Color.RED },
        { row: 12, col: 9, color: Color.RED },
        { row: 13, col: 9, color: Color.RED },
        { row: 14, col: 9, color: Color.RED },

        { row: 1, col: 10, color: Color.BLUE },
        { row: 2, col: 10, color: Color.RED },
        { row: 3, col: 10, color: Color.RED },
        { row: 4, col: 10, color: Color.RED },
        { row: 5, col: 10, color: Color.RED },
        { row: 6, col: 10, color: Color.RED },
        { row: 7, col: 10, color: Color.RED },
        { row: 8, col: 10, color: Color.RED },
        { row: 9, col: 10, color: Color.RED },
        { row: 10, col: 10, color: Color.RED },
        { row: 11, col: 10, color: Color.RED },
        { row: 12, col: 10, color: Color.RED },
        { row: 13, col: 10, color: Color.RED },

        { row: 1, col: 11, color: Color.NONE },
        { row: 2, col: 11, color: Color.NONE },
        { row: 3, col: 11, color: Color.NONE },
        { row: 4, col: 11, color: Color.NONE },
        { row: 5, col: 11, color: Color.BLUE },
        { row: 6, col: 11, color: Color.RED },
        { row: 7, col: 11, color: Color.RED },
        { row: 8, col: 11, color: Color.RED },
        { row: 9, col: 11, color: Color.RED },
        { row: 10, col: 11, color: Color.RED },
        { row: 11, col: 11, color: Color.RED },
        { row: 12, col: 11, color: Color.RED },

        { row: 1, col: 12, color: Color.NONE },
        { row: 2, col: 12, color: Color.BLUE },
        { row: 3, col: 12, color: Color.RED },
        { row: 4, col: 12, color: Color.RED },
        { row: 5, col: 12, color: Color.RED },
        { row: 6, col: 12, color: Color.RED },
        { row: 7, col: 12, color: Color.RED },
        { row: 8, col: 12, color: Color.RED },
        { row: 9, col: 12, color: Color.RED },
        { row: 10, col: 12, color: Color.RED },
        { row: 11, col: 12, color: Color.RED },

        { row: 1, col: 13, color: Color.NONE },
        { row: 2, col: 13, color: Color.NONE },
        { row: 3, col: 13, color: Color.NONE },
        { row: 4, col: 13, color: Color.NONE },
        { row: 5, col: 13, color: Color.NONE },
        { row: 6, col: 13, color: Color.BLUE },
        { row: 7, col: 13, color: Color.RED },
        { row: 8, col: 13, color: Color.RED },
        { row: 9, col: 13, color: Color.RED },
        { row: 10, col: 13, color: Color.RED },
    ],
    stars: [
        { row: 7, col: 1 },
        { row: 1, col: 2 },
        { row: 3, col: 3 },
        { row: 7, col: 4 },
        { row: 1, col: 5 },
        { row: 4, col: 6 },
        { row: 6, col: 7 },
        { row: 3, col: 8 },
        { row: 4, col: 9 },
        { row: 1, col: 10 },
        { row: 5, col: 11 },
        { row: 2, col: 12 },
        { row: 6, col: 13 },
    ]
}
export default level
