import { Level } from "../store";

const level: Level = {
  ship: {
      row: 10, col: 1, dir: "TOP"
  },
  functions: [5, 5],
  paints: { red: false, green: false, blue: false },
  cells: [
      { row: 1, col: 1, color: "NONE" },
      { row: 2, col: 1, color: "NONE" },
      { row: 3, col: 1, color: "NONE" },
      { row: 4, col: 1, color: "NONE" },
      { row: 5, col: 1, color: "NONE" },
      { row: 6, col: 1, color: "NONE" },
      { row: 7, col: 1, color: "BLUE" },
      { row: 8, col: 1, color: "RED" },
      { row: 9, col: 1, color: "RED" },
      { row: 10, col: 1, color: "RED" },

      { row: 1, col: 2, color: "BLUE" },
      { row: 2, col: 2, color: "RED" },
      { row: 3, col: 2, color: "RED" },
      { row: 4, col: 2, color: "RED" },
      { row: 5, col: 2, color: "RED" },
      { row: 6, col: 2, color: "RED" },
      { row: 7, col: 2, color: "RED" },
      { row: 8, col: 2, color: "RED" },
      { row: 9, col: 2, color: "RED" },
      { row: 10, col: 2, color: "RED" },
      { row: 11, col: 2, color: "RED" },

      { row: 1, col: 3, color: "NONE" },
      { row: 2, col: 3, color: "NONE" },
      { row: 3, col: 3, color: "BLUE" },
      { row: 4, col: 3, color: "RED" },
      { row: 5, col: 3, color: "RED" },
      { row: 6, col: 3, color: "RED" },
      { row: 7, col: 3, color: "RED" },
      { row: 8, col: 3, color: "RED" },
      { row: 9, col: 3, color: "RED" },
      { row: 10, col: 3, color: "RED" },
      { row: 11, col: 3, color: "RED" },
      { row: 12, col: 3, color: "RED" },

      { row: 1, col: 4, color: "NONE" },
      { row: 2, col: 4, color: "NONE" },
      { row: 3, col: 4, color: "NONE" },
      { row: 4, col: 4, color: "NONE" },
      { row: 5, col: 4, color: "NONE" },
      { row: 6, col: 4, color: "NONE" },
      { row: 7, col: 4, color: "BLUE" },
      { row: 8, col: 4, color: "RED" },
      { row: 9, col: 4, color: "RED" },
      { row: 10, col: 4, color: "RED" },
      { row: 11, col: 4, color: "RED" },
      { row: 12, col: 4, color: "RED" },
      { row: 13, col: 4, color: "RED" },

      { row: 1, col: 5, color: "BLUE" },
      { row: 2, col: 5, color: "RED" },
      { row: 3, col: 5, color: "RED" },
      { row: 4, col: 5, color: "RED" },
      { row: 5, col: 5, color: "RED" },
      { row: 6, col: 5, color: "RED" },
      { row: 7, col: 5, color: "RED" },
      { row: 8, col: 5, color: "RED" },
      { row: 9, col: 5, color: "RED" },
      { row: 10, col: 5, color: "RED" },
      { row: 11, col: 5, color: "RED" },
      { row: 12, col: 5, color: "RED" },
      { row: 13, col: 5, color: "RED" },
      { row: 14, col: 5, color: "RED" },

      { row: 1, col: 6, color: "NONE" },
      { row: 2, col: 6, color: "NONE" },
      { row: 3, col: 6, color: "NONE" },
      { row: 4, col: 6, color: "BLUE" },
      { row: 5, col: 6, color: "RED" },
      { row: 6, col: 6, color: "RED" },
      { row: 7, col: 6, color: "RED" },
      { row: 8, col: 6, color: "RED" },
      { row: 9, col: 6, color: "RED" },
      { row: 10, col: 6, color: "RED" },
      { row: 11, col: 6, color: "RED" },
      { row: 12, col: 6, color: "RED" },
      { row: 13, col: 6, color: "RED" },
      { row: 14, col: 6, color: "RED" },
      { row: 15, col: 6, color: "RED" },

      { row: 1, col: 7, color: "NONE" },
      { row: 2, col: 7, color: "NONE" },
      { row: 3, col: 7, color: "NONE" },
      { row: 4, col: 7, color: "NONE" },
      { row: 5, col: 7, color: "NONE" },
      { row: 6, col: 7, color: "BLUE" },
      { row: 7, col: 7, color: "RED" },
      { row: 8, col: 7, color: "RED" },
      { row: 9, col: 7, color: "RED" },
      { row: 10, col: 7, color: "RED" },
      { row: 11, col: 7, color: "RED" },
      { row: 12, col: 7, color: "RED" },
      { row: 13, col: 7, color: "RED" },
      { row: 14, col: 7, color: "RED" },
      { row: 15, col: 7, color: "RED" },

      { row: 1, col: 8, color: "NONE" },
      { row: 2, col: 8, color: "NONE" },
      { row: 3, col: 8, color: "BLUE" },
      { row: 4, col: 8, color: "RED" },
      { row: 5, col: 8, color: "RED" },
      { row: 6, col: 8, color: "RED" },
      { row: 7, col: 8, color: "RED" },
      { row: 8, col: 8, color: "RED" },
      { row: 9, col: 8, color: "RED" },
      { row: 10, col: 8, color: "RED" },
      { row: 11, col: 8, color: "RED" },
      { row: 12, col: 8, color: "RED" },
      { row: 13, col: 8, color: "RED" },
      { row: 14, col: 8, color: "RED" },
      { row: 15, col: 8, color: "RED" },

      { row: 1, col: 9, color: "NONE" },
      { row: 2, col: 9, color: "NONE" },
      { row: 3, col: 9, color: "NONE" },
      { row: 4, col: 9, color: "BLUE" },
      { row: 5, col: 9, color: "RED" },
      { row: 6, col: 9, color: "RED" },
      { row: 7, col: 9, color: "RED" },
      { row: 8, col: 9, color: "RED" },
      { row: 9, col: 9, color: "RED" },
      { row: 10, col: 9, color: "RED" },
      { row: 11, col: 9, color: "RED" },
      { row: 12, col: 9, color: "RED" },
      { row: 13, col: 9, color: "RED" },
      { row: 14, col: 9, color: "RED" },

      { row: 1, col: 10, color: "BLUE" },
      { row: 2, col: 10, color: "RED" },
      { row: 3, col: 10, color: "RED" },
      { row: 4, col: 10, color: "RED" },
      { row: 5, col: 10, color: "RED" },
      { row: 6, col: 10, color: "RED" },
      { row: 7, col: 10, color: "RED" },
      { row: 8, col: 10, color: "RED" },
      { row: 9, col: 10, color: "RED" },
      { row: 10, col: 10, color: "RED" },
      { row: 11, col: 10, color: "RED" },
      { row: 12, col: 10, color: "RED" },
      { row: 13, col: 10, color: "RED" },

      { row: 1, col: 11, color: "NONE" },
      { row: 2, col: 11, color: "NONE" },
      { row: 3, col: 11, color: "NONE" },
      { row: 4, col: 11, color: "NONE" },
      { row: 5, col: 11, color: "BLUE" },
      { row: 6, col: 11, color: "RED" },
      { row: 7, col: 11, color: "RED" },
      { row: 8, col: 11, color: "RED" },
      { row: 9, col: 11, color: "RED" },
      { row: 10, col: 11, color: "RED" },
      { row: 11, col: 11, color: "RED" },
      { row: 12, col: 11, color: "RED" },

      { row: 1, col: 12, color: "NONE" },
      { row: 2, col: 12, color: "BLUE" },
      { row: 3, col: 12, color: "RED" },
      { row: 4, col: 12, color: "RED" },
      { row: 5, col: 12, color: "RED" },
      { row: 6, col: 12, color: "RED" },
      { row: 7, col: 12, color: "RED" },
      { row: 8, col: 12, color: "RED" },
      { row: 9, col: 12, color: "RED" },
      { row: 10, col: 12, color: "RED" },
      { row: 11, col: 12, color: "RED" },

      { row: 1, col: 13, color: "NONE" },
      { row: 2, col: 13, color: "NONE" },
      { row: 3, col: 13, color: "NONE" },
      { row: 4, col: 13, color: "NONE" },
      { row: 5, col: 13, color: "NONE" },
      { row: 6, col: 13, color: "BLUE" },
      { row: 7, col: 13, color: "RED" },
      { row: 8, col: 13, color: "RED" },
      { row: 9, col: 13, color: "RED" },
      { row: 10, col: 13, color: "RED" },
  ],
  stars: [
      { row: 7, col: 1 },
      { row: 1, col: 2 },
      { row: 3, col: 3 },
      { row: 7, col: 4 },
      { row: 1, col: 5 },
      { row: 4, col: 6 },
      { row: 6, col: 7 },
      { row: 3, col: 8 },
      { row: 4, col: 9 },
      { row: 1, col: 10 },
      { row: 5, col: 11 },
      { row: 2, col: 12 },
      { row: 6, col: 13 },
  ]
}
export default level
