name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: '15.x'
      - name: install dependencies
        run: npm ci
      - name: build /dist folder
        run: npm run build
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: add builded /dist folder
        run: git add dist
      - name: commit /dist folder
        run: git commit -m 'adding dist subtree'
      - name: add /dist folder to subtree
        run: git subtree push --prefix dist origin gh-pages
